apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp
data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: bankappdb
  OLLAMA_URL: http://ollama-service:11434
  SERVER_FORWARD_HEADERS_STRATEGY: native
